### ISSUE TITLE
Hi I like your code. However, what is a ticket ID??

### ISSUE THREAD

**Issue by yc1838** [0xZDH/EventBot#1]
^as title

**Comment by 0xZDH** [comment]
The ticket ID is the numerical value attached to a ticket type within Eventbrite when selecting a ticket for purchase. After selecting "Get tickets" for a given event, a modal opens with the different ticket options and the quantity of each ticket is available as a drop down. The attribute ID of each drop down has a value of "ticket-quantity-selector-ID" where ID is the numerical value that EventBot is expecting to use when searching for the right ticket to purchase.
